name: Unit Test

# Trigger event for action
on: push


jobs:
    install-docker:
        runs-on: ubuntu-latest
        steps:
            - name: Check out this repo
              uses: actions/checkout@v3
            
            - name: Build Docker image
              run: docker build -t unit-test-image -f Dockerfile .
            
            - name: Run Docker Image
              run: docker run --tm unti-test-image
